feat: Add `test-connection` command (#17086)
#### Summary

Work in progress for https://github.com/cloudquery/cloudquery/issues/15704 and also https://github.com/cloudquery/cloudquery-issues/issues/1170 (internal issue).

This command uses the built in `init` gRPC call to validate plugin initialization. This relies on plugins to do all the relevant checks during init. Some plugins do it, some don't so we'll need to add plugin's support for it.

Example for AWS->Postgres without AWS creds and wrong Postgres password:

```
Loading spec(s) from examples/aws-postgres.yml
Error: failed to init source aws (cloudquery/aws@v23.1.0): rpc error: code = Internal desc = failed to init plugin: failed to initialize client: no AWS accounts were successfully configured. See warning messages in the logs for details
failed to init destination postgresql (cloudquery/postgresql@v7.2.0): rpc error: code = Internal desc = failed to init plugin: failed to initialize client: failed to get current database: failed to connect to `host=localhost user=postgres database=postgres`: failed SASL auth (FATAL: password authentication failed for user "postgres" (SQLSTATE 28P01))
exit status 1
```