fix(cdc): Allow dashes in source names when using Postgres CDC (#11219)
Currently using a dash in the source spec name field causes an error when using Postgres source with CDC:

```
Error: failed to sync v1 source name-dash: rpc error: code = Unknown desc = failed to sync resources: failed to sync unmanaged client: failed to create replication slot pg-motherduck with pgerror severity: ERROR, code: 42601, message: syntax error, detail :, hint: , position: 0, internal_position: 0, internal_query: , where: , schema_name: , table_name: , column_name: , data_type_name: , constraint_name: , file: repl_scanner.l, line: 246, routine: replication_yyerror: ERROR: syntax error (SQLSTATE 42601)
```

Generally we don't have such restrictions on the source name, so this change fixes it so that dashes are replaced with underscores when creating the replication slot.