fix: DuckDB connections to Motherduck failing due to outdated extension version. (#18856)
Fixes the extension version 0.9 -> 0.10 upgrade in order to support Motherduck connections

```
➜  config cloudquery test-connection src/k8s-local.yml dst/motherduck-cloud.yml
Loading spec(s) from src/k8s-local.yml, dst/motherduck-cloud.yml
Test Connection Results
source       k8s (grpc@localhost:7777)         Success
destination  motherduck (grpc@localhost:7001)  Failure: UNKNOWN          could not open database: Invalid Input Error: Initialization function "motherduck_init" from file "/root/.duckdb/extensions/v0.9.2/linux_arm64/motherduck.duckdb_extension" threw an exception: "Invalid Input Error: Initialization function "motherduck_init" from file "/root/.duckdb/extensions/v0.9.2/linux_arm64/motherduck.v1.15.29.duckdb_extension" threw an exception: "Invalid Error: Your MotherDuck extension is running on DuckDB v0.9.2 which is no longer supported. Please upgrade your DuckDB. We recommend DuckDB v1.0.0. For the installation guide, please refer to https://duckdb.org/docs/installation/. (you are using version v1.15.29)""
Error: at least one test connection failed
➜  config cloudquery test-connection src/k8s-local.yml dst/motherduck-cloud.yml
Loading spec(s) from src/k8s-local.yml, dst/motherduck-cloud.yml
Test Connection Results
source       k8s (grpc@localhost:7777)         Success
destination  motherduck (grpc@localhost:7001)  Success
```