feat: Add Snowflake connection test (#18558)
#### Summary
Implements connection testing for snowflake.

```sh
> cloudquery test-connection snowflake.yaml
Loading spec(s) from snowflake.yaml
Test Connection Results
destination  snowflake (grpc@localhost:7777)  Failure: UNAUTHORIZED 	 390201 (08004): The requested database does not exist or not authorized.
Error: at least one test connection failed

> cloudquery test-connection snowflake.yaml
Loading spec(s) from snowflake.yaml
Test Connection Results
destination  snowflake (grpc@localhost:7777)  Success
```

Closes https://github.com/cloudquery/cloudquery-issues/issues/2012