feat: Better summary of schema changes (#21165)
#### Summary

Follow up to https://github.com/cloudquery/plugin-sdk/pull/2240

Example error

```
Loading spec(s) from examples/gcp_to_postgres.yml
Starting migration for: gcp (cloudquery/gcp@v18.20.1) -> [postgresql (grpc@localhost:8888)]
Error: failed to migrate v3 source gcp: rpc error: code = Internal desc = write failed: 
Can't migrate tables automatically, migrate manually or consider using 'migrate_mode: forced'. Non auto migratable tables changes:

gcp_artifactregistry_docker_images:
  - Type changed from "list<item: utf8, nullable>" to "json" for column "tags"

gcp_compute_routes:
  - Column "next_hop_inter_region_cost" added with type "int64"
  - Column "next_hop_med" added with type "int64"
  - Column "next_hop_origin" added with type "utf8"
  - Type changed from "list<item: utf8, nullable>" to "json" for column "tags"
```