feat: Add `exit_immediately` spec option to all test plugins. (#19865)
This PR adds spec options on all test plugins to cause an `os.Exit(1)` upon syncing, to enable e2e testing in the `cli`.

The spec option is a boolean called `exit_immediately`, except in the destination test plugin which has granular options for erroring already (write, insert, migrate), so in this case I added analogous `exit` versions.

I tested the options by running syncs which each component exiting (source, destination, transformer):

### Source exits on sync immediately

```bash
$ cli sync testdata
Loading spec(s) from testdata
Starting sync for: test (local@./test) -> [test-destination (grpc@localhost:7778)]
source plugin process failed with exit status 1
Error: failed to sync v3 source test: unexpected error from sync client receive: rpc error: code = Unavailable desc = error reading from server: EOF
```

### Destination exits on insert

```bash
$ cli sync testdata
Loading spec(s) from testdata
Starting sync for: test (local@./test) -> [test-destination (grpc@localhost:7778)]
Error: failed to sync v3 source test: write client returned error (migrate): error reading from server: EOF
```

### Transformer exits on transform

```bash
$ cli sync testdata
Loading spec(s) from testdata
Starting sync for: test (local@./test) -> [test-destination (grpc@localhost:7778)]
Error: failed to sync v3 source test: rpc error: code = Unavailable desc = error reading from server: EOF
```