fix(deps): Update dependency prettier to v3.8.1 (#21899)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [prettier](https://prettier.io) ([source](https://redirect.github.com/prettier/prettier)) | devDependencies | minor | [`3.3.3` -> `3.8.1`](https://renovatebot.com/diffs/npm/prettier/3.3.3/3.8.1) |

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency Dashboard for more information.

---

### Release Notes

<details>
<summary>prettier/prettier (prettier)</summary>

### [`v3.8.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#381)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.8.0...3.8.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.8.0...3.8.1)

##### Include available `printers` in plugin type declarations ([#&#8203;18706](https://redirect.github.com/prettier/prettier/pull/18706) by [@&#8203;porada](https://redirect.github.com/porada))



```ts
// Input
import * as prettierPluginEstree from "prettier/plugins/estree";

// Prettier 3.8.0
// Property 'printers' does not exist on type 'typeof import("prettier/plugins/estree")'. ts(2339)
prettierPluginEstree.printers.estree; //=> any

// Prettier 3.8.1
prettierPluginEstree.printers.estree; //=> Printer
prettierPluginEstree.printers["estree-json"]; //=> Printer
```

### [`v3.8.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#380)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.7.4...3.8.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.7.4...3.8.0)

🔗 [Release Notes](https://prettier.io/blog/2026/01/14/3.8.0)

### [`v3.7.4`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#374)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.7.3...3.7.4)

[diff](https://redirect.github.com/prettier/prettier/compare/3.7.3...3.7.4)

##### LWC: Avoid quote around interpolations ([#&#8203;18383](https://redirect.github.com/prettier/prettier/pull/18383) by [@&#8203;kovsu](https://redirect.github.com/kovsu))



```html
<!-- Input -->
<div foo={bar}>   </div>

<!-- Prettier 3.7.3 (--embedded-language-formatting off) -->
<div foo="{bar}"></div>

<!-- Prettier 3.7.4 (--embedded-language-formatting off) -->
<div foo={bar}></div>
```

##### TypeScript: Fix comment inside union type gets duplicated ([#&#8203;18393](https://redirect.github.com/prettier/prettier/pull/18393) by [@&#8203;fisker](https://redirect.github.com/fisker))



```tsx
// Input
type Foo = (/** comment */ a | b) | c;

// Prettier 3.7.3
type Foo = /** comment */ (/** comment */ a | b) | c;

// Prettier 3.7.4
type Foo = /** comment */ (a | b) | c;
```

##### TypeScript: Fix unstable comment print in union type comments ([#&#8203;18395](https://redirect.github.com/prettier/prettier/pull/18395) by [@&#8203;fisker](https://redirect.github.com/fisker))



```tsx
// Input
type X = (A | B) & (
  // comment
  A | B
);

// Prettier 3.7.3 (first format)
type X = (A | B) &
  (// comment
  A | B);

// Prettier 3.7.3 (second format)
type X = (
  | A
  | B // comment
) &
  (A | B);

// Prettier 3.7.4
type X = (A | B) &
  // comment
  (A | B);
```

### [`v3.7.3`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#373)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.7.2...3.7.3)

[diff](https://redirect.github.com/prettier/prettier/compare/3.7.2...3.7.3)

##### API: Fix `prettier.getFileInfo()` change that breaks VSCode extension ([#&#8203;18375](https://redirect.github.com/prettier/prettier/pull/18375) by [@&#8203;fisker](https://redirect.github.com/fisker))

An internal refactor accidentally broke the VSCode extension plugin loading.

### [`v3.7.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#372)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.7.1...3.7.2)

[diff](https://redirect.github.com/prettier/prettier/compare/3.7.1...3.7.2)

##### JavaScript: Fix string print when switching quotes ([#&#8203;18351](https://redirect.github.com/prettier/prettier/pull/18351) by [@&#8203;fisker](https://redirect.github.com/fisker))



```jsx
// Input
console.log("A descriptor\\'s .kind must be \"method\" or \"field\".")

// Prettier 3.7.1
console.log('A descriptor\\'s .kind must be "method" or "field".');

// Prettier 3.7.2
console.log('A descriptor\\\'s .kind must be "method" or "field".');
```

##### JavaScript: Preserve quote for embedded HTML attribute values ([#&#8203;18352](https://redirect.github.com/prettier/prettier/pull/18352) by [@&#8203;kovsu](https://redirect.github.com/kovsu))



```tsx
// Input
const html = /* HTML */ ` <div class="${styles.banner}"></div> `;

// Prettier 3.7.1
const html = /* HTML */ ` <div class=${styles.banner}></div> `;

// Prettier 3.7.2
const html = /* HTML */ ` <div class="${styles.banner}"></div> `;
```

##### TypeScript: Fix comment in empty type literal ([#&#8203;18364](https://redirect.github.com/prettier/prettier/pull/18364) by [@&#8203;fisker](https://redirect.github.com/fisker))



```tsx
// Input
export type XXX = {
  // tbd
};

// Prettier 3.7.1
export type XXX = { // tbd };

// Prettier 3.7.2
export type XXX = {
  // tbd
};
```

### [`v3.7.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#371)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.7.0...3.7.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.7.0...3.7.1)

##### API: Fix performance regression in doc printer ([#&#8203;18342](https://redirect.github.com/prettier/prettier/pull/18342) by [@&#8203;fisker](https://redirect.github.com/fisker))

Prettier 3.7.0 can be very slow when formatting big files, the regression has been fixed.

### [`v3.7.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#370)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.6.2...3.7.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.6.2...3.7.0)

🔗 [Release Notes](https://prettier.io/blog/2025/11/27/3.7.0)

### [`v3.6.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#362)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)

[diff](https://redirect.github.com/prettier/prettier/compare/3.6.1...3.6.2)

##### Markdown: Add missing blank line around code block ([#&#8203;17675](https://redirect.github.com/prettier/prettier/pull/17675) by [@&#8203;fisker](https://redirect.github.com/fisker))



````md
<!-- Input -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List

<!-- Prettier 3.6.1 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```
   1. Another
   2. List

<!-- Prettier 3.6.2 -->
1. Some text, and code block below, with newline after code block

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List
````

### [`v3.6.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#361)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.6.0...3.6.1)

##### TypeScript: Allow const without initializer ([#&#8203;17650](https://redirect.github.com/prettier/prettier/pull/17650), [#&#8203;17654](https://redirect.github.com/prettier/prettier/pull/17654) by [@&#8203;fisker](https://redirect.github.com/fisker))



```jsx
// Input
export const version: string;

// Prettier 3.6.0 (--parser=babel-ts)
SyntaxError: Unexpected token (1:21)
> 1 | export const version: string;
    |                     ^

// Prettier 3.6.0 (--parser=oxc-ts)
SyntaxError: Missing initializer in const declaration (1:14)
> 1 | export const version: string;
    |              ^^^^^^^^^^^^^^^

// Prettier 3.6.1
export const version: string;
```

##### Miscellaneous: Avoid closing files multiple times ([#&#8203;17665](https://redirect.github.com/prettier/prettier/pull/17665) by [@&#8203;43081j](https://redirect.github.com/43081j))

When reading a file to infer the interpreter from a shebang, we use the
`n-readlines` library to read the first line in order to get the shebang.

This library closes files when it reaches EOF, and we later try close the same
files again. We now close files only if `n-readlines` did not already close
them.

### [`v3.6.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#360)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.5.3...3.6.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.5.3...3.6.0)

🔗 [Release Notes](https://prettier.io/blog/2025/06/23/3.6.0)

### [`v3.5.3`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#353)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.5.2...3.5.3)

[diff](https://redirect.github.com/prettier/prettier/compare/3.5.2...3.5.3)

##### Flow: Fix missing parentheses in `ConditionalTypeAnnotation` ([#&#8203;17196](https://redirect.github.com/prettier/prettier/pull/17196) by [@&#8203;fisker](https://redirect.github.com/fisker))



```jsx
// Input
type T<U> = 'a' | ('b' extends U ? 'c' : empty);
type T<U> = 'a' & ('b' extends U ? 'c' : empty);

// Prettier 3.5.2
type T<U> = "a" | "b" extends U ? "c" : empty;
type T<U> = "a" & "b" extends U ? "c" : empty;

// Prettier 3.5.3
type T<U> = "a" | ("b" extends U ? "c" : empty);
type T<U> = "a" & ("b" extends U ? "c" : empty);
```

### [`v3.5.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#352)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.5.1...3.5.2)

[diff](https://redirect.github.com/prettier/prettier/compare/3.5.1...3.5.2)

##### Remove `module-sync` condition ([#&#8203;17156](https://redirect.github.com/prettier/prettier/pull/17156) by [@&#8203;fisker](https://redirect.github.com/fisker))

In Prettier 3.5.0, [we added `module-sync` condition to `package.json`](https://prettier.io/blog/2025/02/09/3.5.0#use-esm-entrypoint-for-requireesm-16958-by-tats-u), so that `require("prettier")` can use ESM version, but turns out it doesn't work if CommonJS and ESM plugins both imports builtin plugins. To solve this problem, we decide simply remove the `module-sync` condition, so `require("prettier")` will still use the CommonJS version, we'll revisit until `require(ESM)` feature is more stable.

### [`v3.5.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#351)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.5.0...3.5.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.5.0...3.5.1)

##### Fix CLI crash when cache for old version exists ([#&#8203;17100](https://redirect.github.com/prettier/prettier/pull/17100) by [@&#8203;sosukesuzuki](https://redirect.github.com/sosukesuzuki))

Prettier 3.5 uses a different cache format than previous versions, Prettier 3.5.0 crashes when reading existing cache file, Prettier 3.5.1 fixed the problem.

##### Support dockercompose and github-actions-workflow in VSCode ([#&#8203;17101](https://redirect.github.com/prettier/prettier/pull/17101) by [@&#8203;remcohaszing](https://redirect.github.com/remcohaszing))

Prettier now supports the `dockercompose` and `github-actions-workflow` languages in Visual Studio Code.

### [`v3.5.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#350)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.4.2...3.5.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.4.2...3.5.0)

🔗 [Release Notes](https://prettier.io/blog/2025/02/09/3.5.0.html)

### [`v3.4.2`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#342)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.4.1...3.4.2)

[diff](https://redirect.github.com/prettier/prettier/compare/3.4.1...3.4.2)

##### Treat U+30A0 & U+30FB in Katakana Block as CJK ([#&#8203;16796](https://redirect.github.com/prettier/prettier/pull/16796) by [@&#8203;tats-u](https://redirect.github.com/tats-u))

Prettier doesn't treat U+30A0 & U+30FB as Japanese. U+30FB is commonly used in Japanese to represent the delimitation of first and last names of non-Japanese people or “and”. The following “C言語・C++・Go・Rust” means “C language & C++ & Go & Rust” in Japanese.



```md
<!-- Input (--prose-wrap=never) -->

C言
語
・
C++
・
Go
・
Rust

<!-- Prettier 3.4.1 -->
C言語・ C++ ・ Go ・ Rust

<!-- Prettier 3.4.2 -->
C言語・C++・Go・Rust
```

U+30A0 can be used as the replacement of the `-` in non-Japanese names (e.g. “Saint-Saëns” (Charles Camille Saint-Saëns) can be represented as “サン゠サーンス” in Japanese), but substituted by ASCII hyphen (U+002D) or U+FF1D (full width hyphen) in many cases (e.g. “サン=サーンス” or “サン＝サーンス”).

##### Fix comments print on class methods with decorators ([#&#8203;16891](https://redirect.github.com/prettier/prettier/pull/16891) by [@&#8203;fisker](https://redirect.github.com/fisker))



```jsx
// Input
class A {
  @&#8203;decorator
  /** 
   * The method description
   *
  */
  async method(foo: Foo, bar: Bar) {
    console.log(foo);
  }
}

// Prettier 3.4.1
class A {
  @&#8203;decorator
  async /**
   * The method description
   *
   */
  method(foo: Foo, bar: Bar) {
    console.log(foo);
  }
}

// Prettier 3.4.2
class A {
  @&#8203;decorator
  /**
   * The method description
   *
   */
  async method(foo: Foo, bar: Bar) {
    console.log(foo);
  }
}
```

##### Fix non-idempotent formatting ([#&#8203;16899](https://redirect.github.com/prettier/prettier/pull/16899) by [@&#8203;seiyab](https://redirect.github.com/seiyab))

This bug fix is not language-specific. You may see similar change in any languages. This fixes regression in 3.4.0 so change caused by it should yield same formatting as 3.3.3.



```jsx
// Input
<div>
  foo
  <span>longlonglonglonglonglonglonglonglonglonglonglonglonglonglongl foo</span>
  , abc
</div>;

// Prettier 3.4.1 (first)
<div>
  foo
  <span>
    longlonglonglonglonglonglonglonglonglonglonglonglonglonglongl foo
  </span>, abc
</div>;

// Prettier 3.4.1 (second)
<div>
  foo
  <span>longlonglonglonglonglonglonglonglonglonglonglonglonglonglongl foo</span>
  , abc
</div>;

// Prettier 3.4.2
<div>
  foo
  <span>longlonglonglonglonglonglonglonglonglonglonglonglonglonglongl foo</span>
  , abc
</div>;
```

### [`v3.4.1`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#341)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.4.0...3.4.1)

[diff](https://redirect.github.com/prettier/prettier/compare/3.4.0...3.4.1)

##### Remove unnecessary parentheses around assignment in `v-on` ([#&#8203;16887](https://redirect.github.com/prettier/prettier/pull/16887) by [@&#8203;fisker](https://redirect.github.com/fisker))



```vue
<!-- Input -->
<template>
  <button @&#8203;click="foo += 2">Click</button>
</template>

<!-- Prettier 3.4.0 -->
<template>
  <button @&#8203;click="(foo += 2)">Click</button>
</template>

<!-- Prettier 3.4.1 -->
<template>
  <button @&#8203;click="foo += 2">Click</button>
</template>
```

### [`v3.4.0`](https://redirect.github.com/prettier/prettier/blob/HEAD/CHANGELOG.md#340)

[Compare Source](https://redirect.github.com/prettier/prettier/compare/3.3.3...3.4.0)

[diff](https://redirect.github.com/prettier/prettier/compare/3.3.3...3.4.0)

🔗 [Release Notes](https://prettier.io/blog/2024/11/26/3.4.0.html)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - Between 12:00 AM and 03:59 AM, on day 1 of the month ( * 0-3 1 * * ) (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://redirect.github.com/renovatebot/renovate).