fix: Resolve plugin version from GitHub registry instead of gRPC call (#1856)
#### Summary

This PR fixes https://github.com/cloudquery/docs/issues/216 which is still present in v2 and causing failures in https://github.com/cloudquery/cloudquery/pull/1848. Also somehow related to https://github.com/cloudquery/cloudquery/issues/908

If you try:
1. `gen source test`
2. `gen destination postgresql`
3. `gen sync .`
you'll get the follow error:
```
Loading specs from directory:  .
Downloading plugin from: https://github.com/cloudquery/cloudquery/releases/download/plugins/source/test/development/test_darwin_arm64.zip to: .cq/plugins/github/cloudquery/test/development/cq-source-test_darwin_arm64.zip 
Error: failed to sync source test: failed to get source plugin client for test: failed to download plugin: bad status: 404 Not Found. downloading https://github.com/cloudquery/cloudquery/releases/download/plugins/source/test/development/test_darwin_arm64.zip
exit status 1
```

This is because the test plugin doesn't embed the version correctly when released (and probably others too), thus reports a `development` version which is embedded in the config:
```yml
kind: "source"
spec:
  # Name of the plugin.
  name: "test"

  # Version of the plugin to use.
  version: "development"
...
```

Then the CLI tries to download that version from GitHub and fails.
Since we already know the version from GitHub I suggest we use that one instead of the gRPC call. For local/gRPC plugins the version is not important (at the moment).
The version is already set in https://github.com/cloudquery/cloudquery/blob/7a83a65446119b5339f5f3a3759f7f160a3716b4/cli/internal/plugins/plugins.go#L137 so I only needed to pass in a pointer

---