fix: When a config file is missing, prompt the user to select run `cloudquery switch <team>` (#18225)
#### Summary

Fixes https://github.com/cloudquery/cloudquery/issues/18224

The CLI output will be (for example):

```
Loading spec(s) from examples/gcp-postgres.yml
Error: failed to get team name: your current team is not set.

Available teams: <team-1>, <team-2>.

To set your current team, run `cloudquery switch <team>`
```